### ISSUE TITLE
[BUG] Character is removed from constant tokens' default delimiter after expansion

### ISSUE THREAD

**Issue by vbalint1892** [gherking/gherkin-ast#39] opened 2023-02-15 10:07 UTC
## Summary
If an Examples table of a scenario outline contains a constant token using the default delimiter ("$$"), then a character is removed from the start and the end of the token's delimiter in the expanded scenario.

## Steps to Reproduce
Please provide the steps to reproduce the behavior:
1. Have a feature file with a scenario outline containing a constant token using the default delimiter e.g. "$$pages.home$$"
2. Execute gherking with "gpc-scenario-outline-expander" precompiler
3. Check the the expanded scenario
Note: the issue is not reproducible when using a custom delimiter (e.g. "++")

### Expected behavior**
The delimiter should be expanded into the scenario unchanged: "$$pages.home$$"

### Actual behavior**
A character is removed from both the delimiter's start and end: "$pages.home$"

**Comment by vbalint1892** [comment] 2023-02-15 13:55
Debug log from "gpc-scenario-outline-expander":
[log_expander.txt](https://github.com/gherking/gpc-scenario-outline-expander/files/10743643/log_expander.txt)

Debug log from "gpc-scenario-outline-expander" and "gherking" for an affected feature file:
[log_gherking.txt](https://github.com/gherking/gpc-scenario-outline-expander/files/10743658/log_gherking.txt)

**Comment by szikszail** [comment] 2023-02-15 16:47
The root cause of the issue is the built-in behavior of `String.prototype.replace`, which handles string with `$` as replace tokens and `$$` as one `$`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement.

Location: https://github.com/gherking/gherkin-ast/blob/master/src/ast/scenarioOutline.ts#L136

Moving to gherking/gherkin-ast.

**Closed as completed** 2023-02-15 17:26 UTC
Labels: bug
